-- ============================================================
-- RSSC Strain Database v2 Schema
-- ============================================================
-- Source of truth: output/analysis_sample_manifest.tsv
-- Primary key: sample_id (= biosample_accession)
-- Generated by: init_db_v2.py
-- ============================================================

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- 1. samples
CREATE TABLE IF NOT EXISTS samples (
    sample_id               TEXT PRIMARY KEY,
    biosample_accession     TEXT NOT NULL,
    sample_id_source        TEXT,
    strain                  TEXT,
    isolate                 TEXT,
    organism_name           TEXT,
    preferred_assembly      TEXT,
    genbank_accession       TEXT,
    refseq_accession        TEXT,
    all_assembly_accessions TEXT,
    n_assemblies            INTEGER,
    duplicate_type          TEXT,
    needs_assembly_qc_review TEXT,
    bioproject_accession    TEXT,
    host_raw                TEXT,
    host_species            TEXT,
    host_cultivar           TEXT,
    country                 TEXT,
    admin1                  TEXT,
    locality                TEXT,
    latitude                REAL,
    longitude               REAL,
    collection_year         INTEGER,
    sra_accessions          TEXT,
    n_sra_runs              INTEGER,
    sequencing_platforms    TEXT,
    sra_lookup_status       TEXT,
    core_metadata_complete  TEXT,
    extended_metadata_complete TEXT,
    needs_manual_review     TEXT,
    pmid                    TEXT,
    doi                     TEXT
);
CREATE INDEX idx_samples_biosample ON samples(biosample_accession);
CREATE INDEX idx_samples_strain ON samples(strain);
CREATE INDEX idx_samples_bioproject ON samples(bioproject_accession);
CREATE INDEX idx_samples_assembly ON samples(preferred_assembly);
CREATE INDEX idx_samples_country ON samples(country);

-- 2. sample_metadata
CREATE TABLE IF NOT EXISTS sample_metadata (
    sample_id               TEXT PRIMARY KEY REFERENCES samples(sample_id),
    assembly_accession      TEXT,
    bioproject_accession    TEXT,
    strain                  TEXT,
    isolate                 TEXT,
    sample_name             TEXT,
    organism_name           TEXT,
    taxid                   INTEGER,
    assembly_level          TEXT,
    release_date            TEXT,
    sequencing_tech         TEXT,
    source_database         TEXT,
    host_raw                TEXT,
    host_species            TEXT,
    host_cultivar           TEXT,
    host_ncbi               TEXT,
    host_ena                TEXT,
    host_conflict           TEXT,
    host_source             TEXT,
    cultivar_ncbi           TEXT,
    cultivar_ena            TEXT,
    cultivar_conflict       TEXT,
    cultivar_source         TEXT,
    isolation_source        TEXT,
    isolation_source_source TEXT,
    geo_loc_name_raw        TEXT,
    country                 TEXT,
    admin1                  TEXT,
    locality                TEXT,
    geo_ncbi                TEXT,
    geo_ena                 TEXT,
    geo_conflict            TEXT,
    geo_relation            TEXT,
    geo_source              TEXT,
    lat_lon_raw             TEXT,
    latitude                REAL,
    longitude               REAL,
    latlon_source           TEXT,
    collection_date_raw     TEXT,
    collection_year         INTEGER,
    collection_date_ncbi    TEXT,
    collection_date_ena     TEXT,
    collection_date_conflict TEXT,
    collection_date_source  TEXT,
    sra_accession           TEXT,
    sra_accessions          TEXT,
    n_sra_runs              INTEGER,
    sra_experiments         TEXT,
    sequencing_platforms    TEXT,
    sequencing_models       TEXT,
    library_strategies      TEXT,
    ena_accession           TEXT,
    sra_source              TEXT,
    sra_lookup_status       TEXT,
    pmid                    TEXT,
    doi                     TEXT,
    metadata_source         TEXT,
    metadata_confidence     TEXT,
    metadata_conflict       TEXT,
    needs_manual_review     TEXT,
    biosample_attributes_json TEXT,
    notes                   TEXT
);
CREATE INDEX idx_meta_assembly ON sample_metadata(assembly_accession);
CREATE INDEX idx_meta_bioproject ON sample_metadata(bioproject_accession);
CREATE INDEX idx_meta_source ON sample_metadata(metadata_source);

-- 3. genome_qc
CREATE TABLE IF NOT EXISTS genome_qc (
    sample_id           TEXT PRIMARY KEY REFERENCES samples(sample_id),
    biosample_accession TEXT,
    preferred_assembly  TEXT,
    assembly_level      TEXT,
    genome_size         REAL,
    num_contigs         REAL,
    largest_contig      REAL,
    N50                 REAL,
    L50                 REAL,
    GC_percent          REAL,
    completeness        REAL,
    contamination       REAL,
    sra_lookup_status   TEXT,
    n_sra_runs          INTEGER,
    qc_status           TEXT,
    qc_notes            TEXT,
    outlier_flags       TEXT
);
CREATE INDEX idx_qc_status ON genome_qc(qc_status);
CREATE INDEX idx_qc_assembly ON genome_qc(preferred_assembly);

-- 4. genome_qc_classification
CREATE TABLE IF NOT EXISTS genome_qc_classification (
    sample_id               TEXT PRIMARY KEY REFERENCES samples(sample_id),
    biosample_accession     TEXT,
    strain                  TEXT,
    preferred_assembly      TEXT,
    assembly_level          TEXT,
    genome_size             REAL,
    num_contigs             REAL,
    N50                     REAL,
    GC_percent              REAL,
    completeness            REAL,
    contamination           REAL,
    qc_class                TEXT,
    qc_reason               TEXT,
    genome_size_outlier     TEXT,
    gc_outlier              TEXT,
    contig_outlier          TEXT,
    n50_outlier             TEXT,
    fragmentation_flag      TEXT,
    low_completeness_flag   TEXT,
    high_contamination_flag TEXT
);
CREATE INDEX idx_class_qc ON genome_qc_classification(qc_class);

-- 5. literature_metadata_candidates
CREATE TABLE IF NOT EXISTS literature_metadata_candidates (
    row_id              INTEGER PRIMARY KEY AUTOINCREMENT,
    sample_id           TEXT NOT NULL REFERENCES samples(sample_id),
    biosample_accession TEXT,
    strain_manifest     TEXT,
    strain_paper        TEXT,
    bioproject_accession TEXT,
    pmid                TEXT,
    doi                 TEXT,
    paper_title         TEXT,
    supplement_file     TEXT,
    sheet_or_table      TEXT,
    row_identifier      TEXT,
    original_column     TEXT,
    original_value      TEXT,
    field               TEXT,
    candidate_value     TEXT,
    match_method        TEXT,
    confidence          TEXT,
    needs_manual_review TEXT
);
CREATE INDEX idx_litcand_sample ON literature_metadata_candidates(sample_id);
CREATE INDEX idx_litcand_field ON literature_metadata_candidates(field);
CREATE INDEX idx_litcand_pmid ON literature_metadata_candidates(pmid);

-- 6. isolate_typing
CREATE TABLE IF NOT EXISTS isolate_typing (
    row_id              INTEGER PRIMARY KEY AUTOINCREMENT,
    sample_id           TEXT NOT NULL REFERENCES samples(sample_id),
    biosample_accession TEXT,
    strain_manifest     TEXT,
    strain_paper        TEXT,
    bioproject_accession TEXT,
    pmid                TEXT,
    doi                 TEXT,
    paper_title         TEXT,
    supplement_file     TEXT,
    sheet_or_table      TEXT,
    row_identifier      TEXT,
    original_column     TEXT,
    original_value      TEXT,
    typing_scheme       TEXT,
    typing_value        TEXT,
    match_method        TEXT,
    confidence          TEXT,
    needs_manual_review TEXT
);
CREATE INDEX idx_typing_sample ON isolate_typing(sample_id);
CREATE INDEX idx_typing_scheme ON isolate_typing(typing_scheme);

-- 7. phenotypes
CREATE TABLE IF NOT EXISTS phenotypes (
    row_id              INTEGER PRIMARY KEY AUTOINCREMENT,
    sample_id           TEXT NOT NULL REFERENCES samples(sample_id),
    biosample_accession TEXT,
    strain              TEXT,
    host_species        TEXT,
    host_cultivar       TEXT,
    trait               TEXT,
    value               TEXT,
    unit                TEXT,
    phenotype_category  TEXT,
    experiment          TEXT,
    condition           TEXT,
    replicate_info      TEXT,
    bioproject_accession TEXT,
    pmid                TEXT,
    doi                 TEXT,
    paper_title         TEXT,
    supplement_file     TEXT,
    sheet_or_table      TEXT,
    row_identifier      TEXT,
    original_column     TEXT,
    original_value      TEXT,
    match_method        TEXT,
    confidence          TEXT,
    needs_manual_review TEXT
);
CREATE INDEX idx_pheno_sample ON phenotypes(sample_id);
CREATE INDEX idx_pheno_trait ON phenotypes(trait);
CREATE INDEX idx_pheno_category ON phenotypes(phenotype_category);

-- 8. bioprojects
CREATE TABLE IF NOT EXISTS bioprojects (
    bioproject_accession       TEXT PRIMARY KEY,
    n_samples                  INTEGER,
    n_unique_biosamples        INTEGER,
    n_unique_strains           INTEGER,
    n_isolates                 INTEGER,
    strain_names               TEXT,
    bioproject_title            TEXT,
    missing_host_count         INTEGER,
    missing_geo_count          INTEGER,
    missing_year_count         INTEGER,
    missing_cultivar_count     INTEGER,
    missing_sra_count          INTEGER,
    core_metadata_complete     TEXT,
    extended_metadata_complete TEXT,
    publication                TEXT,
    pmid                       TEXT,
    doi                        TEXT,
    literature_status          TEXT
);
CREATE INDEX idx_bp_status ON bioprojects(literature_status);

-- 9. publications
CREATE TABLE IF NOT EXISTS publications (
    row_id                     INTEGER PRIMARY KEY AUTOINCREMENT,
    bioproject_accession       TEXT NOT NULL REFERENCES bioprojects(bioproject_accession),
    n_samples                  INTEGER,
    n_unique_strains           INTEGER,
    bioproject_title            TEXT,
    pmid                       TEXT,
    doi                        TEXT,
    paper_title                TEXT,
    journal                    TEXT,
    publication_year           INTEGER,
    authors                    TEXT,
    publication_status         TEXT,
    evidence_source            TEXT,
    evidence_url               TEXT,
    match_basis                TEXT,
    confidence                 TEXT,
    needs_manual_review        TEXT,
    supplement_search_priority TEXT,
    notes                      TEXT,
    relation_type              TEXT,
    relation_confidence        TEXT,
    organism_manifest          TEXT,
    organism_paper             TEXT,
    organism_relation          TEXT,
    n_manifest_samples         INTEGER,
    n_strain_overlap           INTEGER,
    n_accession_overlap        INTEGER,
    strain_overlap_fraction    REAL,
    relation_evidence          TEXT,
    needs_relation_review      TEXT
);
CREATE INDEX idx_pub_bp ON publications(bioproject_accession);
CREATE INDEX idx_pub_pmid ON publications(pmid);
CREATE INDEX idx_pub_doi ON publications(doi);
CREATE INDEX idx_pub_rel ON publications(relation_type);

-- 10. manual_literature_review
CREATE TABLE IF NOT EXISTS manual_literature_review (
    row_id INTEGER PRIMARY KEY AUTOINCREMENT,
    priority_rank INTEGER,
    review_priority TEXT,
    bioproject_accession TEXT NOT NULL REFERENCES bioprojects(bioproject_accession),
    n_samples INTEGER,
    n_unique_strains INTEGER,
    organism_name TEXT,
    strain_examples TEXT,
    existing_bioproject_title TEXT,
    candidate_paper_count INTEGER,
    candidate_pmids TEXT,
    candidate_dois TEXT,
    candidate_titles TEXT,
    candidate_journals TEXT,
    candidate_years TEXT,
    best_candidate_title TEXT,
    best_candidate_pmid TEXT,
    best_candidate_doi TEXT,
    best_candidate_url TEXT,
    current_match_basis TEXT,
    current_relation_guess TEXT,
    core_metadata_complete_rate REAL,
    missing_host_count INTEGER,
    missing_geo_count INTEGER,
    missing_year_count INTEGER,
    missing_cultivar_count INTEGER,
    has_existing_supplement TEXT,
    existing_supplement_count INTEGER,
    has_existing_metadata_candidates TEXT,
    metadata_candidate_count INTEGER,
    has_existing_typing_candidates TEXT,
    typing_candidate_count INTEGER,
    has_existing_phenotype_candidates TEXT,
    phenotype_candidate_count INTEGER,
    has_raw_reads_count INTEGER,
    manual_relation TEXT,
    manual_primary_paper_title TEXT,
    manual_pmid TEXT,
    manual_doi TEXT,
    manual_evidence TEXT,
    manual_supplement_url TEXT,
    manual_supplement_downloaded TEXT,
    manual_has_metadata TEXT,
    manual_has_typing TEXT,
    manual_has_phenotype TEXT,
    manual_review_status TEXT,
    manual_notes TEXT,
    manual_candidate_is_relevant TEXT,
    manual_priority_override TEXT
);
CREATE INDEX idx_mlr_bp ON manual_literature_review(bioproject_accession);
CREATE INDEX idx_mlr_status ON manual_literature_review(manual_review_status);

-- 11. sample_fasta_map
CREATE TABLE IF NOT EXISTS sample_fasta_map (
    sample_id           TEXT PRIMARY KEY REFERENCES samples(sample_id),
    biosample_accession TEXT,
    preferred_assembly  TEXT,
    original_fasta_name TEXT,
    fasta_path          TEXT
);

-- 12a. genome_rescue_candidates
CREATE TABLE IF NOT EXISTS genome_rescue_candidates (
    sample_id            TEXT PRIMARY KEY REFERENCES samples(sample_id),
    strain               TEXT,
    biosample_accession  TEXT,
    preferred_assembly   TEXT,
    qc_class             TEXT,
    qc_reason            TEXT,
    genome_size          REAL,
    num_contigs          REAL,
    N50                  REAL,
    GC_percent           REAL,
    completeness         REAL,
    contamination        REAL,
    sra_accessions       TEXT,
    n_sra_runs           INTEGER,
    sequencing_platforms TEXT
);

-- 12b. genome_rescue_read_audit
CREATE TABLE IF NOT EXISTS genome_rescue_read_audit (
    row_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sample_id TEXT NOT NULL REFERENCES samples(sample_id),
    strain TEXT,
    biosample_accession TEXT,
    qc_class TEXT,
    qc_reason TEXT,
    preferred_assembly TEXT,
    genome_size REAL,
    num_contigs REAL,
    N50 REAL,
    GC_percent REAL,
    completeness REAL,
    contamination REAL,
    sra_run TEXT,
    experiment TEXT,
    n_runs INTEGER,
    library_strategy TEXT,
    library_source TEXT,
    library_layout TEXT,
    library_selection TEXT,
    sequencing_platform TEXT,
    instrument_model TEXT,
    insert_size TEXT,
    spots INTEGER,
    bases INTEGER,
    avg_read_length REAL,
    spots_with_mates INTEGER,
    estimated_coverage_x REAL,
    read_type_classification TEXT,
    merge_runs_for_assembly TEXT,
    data_issues TEXT,
    recommended_rescue_strategy TEXT
);
CREATE INDEX idx_audit_sample ON genome_rescue_read_audit(sample_id);

-- 12c. genome_rescue_read_plan
CREATE TABLE IF NOT EXISTS genome_rescue_read_plan (
    row_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sample_id TEXT NOT NULL REFERENCES samples(sample_id),
    strain TEXT,
    sra_run TEXT,
    platform TEXT,
    model TEXT,
    library_layout TEXT,
    library_strategy TEXT,
    spots INTEGER,
    bases_Gb REAL,
    avg_read_length REAL,
    is_illumina TEXT,
    is_paired_end TEXT,
    is_long_read TEXT,
    n_runs INTEGER,
    qc_class TEXT,
    completeness REAL,
    contamination REAL,
    genome_size REAL,
    num_contigs REAL,
    N50 REAL,
    qc_issues TEXT,
    recommended_rescue_strategy TEXT,
    notes TEXT
);
CREATE INDEX idx_plan_sample ON genome_rescue_read_plan(sample_id);
